# Generated by Django 2.1.3 on 2018-12-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tamanioscantidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanioscantidades',
            old_name='producto',
            new_name='product',
        ),
    ]
