# Generated by Django 2.1.3 on 2018-12-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181212_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanioscantidades',
            old_name='product',
            new_name='producto',
        ),
    ]
