# Generated by Django 2.1.3 on 2018-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181212_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizequantity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
