# Generated by Django 2.1.3 on 2018-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(choices=[('50mm x 50mm', '50 mm x 50 mm'), ('75mm x 75mm', '75 mm x 75 mm'), ('100mm x 100mm', '100 mm x 100 mm'), ('125mm x 125mm', '125 mm x 125 mm')], max_length=20),
        ),
    ]
