# Generated by Django 2.1.3 on 2018-12-02 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20181202_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
